logging:
  level:
    root: info

server:
  ssl:
    enabled: false
  port: 1133

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:54321/rajdownik_dev
    username: witta
    password: witta
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: update

rajdownik:
  auth:
    jwtSecret: 688dc1754ba81961938cee3adb5b1b68167c1cf5531f6da17490b550b6465fb8