logging:
  level:
    root: info

server:
  ssl:
    enabled: false
  port: 1144

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://185.238.75.202:54321/rajdownik_dev
    username: witta
    password: witta
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rajdownik:
  auth:
    jwtSecret: 688dc1754ba81961938cee3adb5b1b68167c1cf5531f6da17490b550b6465fb8
  frontend-url: