services:
  backend:
    build: ./backend
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgres://witta:witta@156.17.197.25:7586/rajdownik_dev
      - SPRING_DATASOURCE_USERNAME=$DATABASE_USER
      - SPRING_DATASOURCE_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
